### PR TITLE
Load raw RT urls into dim feeds

### PR DESCRIPTION
**Pull request by evansiroky**
This is a work in progress until it can be figured out how to match the raw feed extraction date with the rest of the data in the dim feeds table.

### CODE REVIEW

**Comment by machow** [comment]
Hey--do you mind linking to the issue this PR is for? I think it might be for reports, but am having trouble remembering 😬

**Comment by evansiroky** [comment]
> Hey--do you mind linking to the issue this PR is for? I think it might be for reports, but am having trouble remembering 😬
> 
> edit: seems like #557, is that right?

Yeah, this would support answering the questions posed in #557 and #566.

**Comment by holly-g** [comment]
@machow and @evansiroky to pair on creating a new table.

**Comment by machow** [comment]
DM'd @evansiroky to see if we can pair on this--here are some of my thoughts for posterity. A lot of this is due to how the gtfs_schedule views need to be tuned to store some big fact tables.

There are some subtle issues with the SQL join, and I'm wondering whether with MSD transitdatabase on the horizon, whether it's worth creating tables in a msd_views dag (with a msd_ or similar prefix) so we can answer high-level feed / org questions without the challenges of plugging into the gtfs_schedule tables (which had to be optimized for storing / joining to a lot of stop times across time)

**Comment by machow** [comment]
@evansiroky following up on our pairing--here's a graph of two ways to get this data in...

image

The big challenge with option 1 (adding to dimension) is that it requires a lot of SQL / careful checking to make sure it was correctly added to dim_feeds, because it is a [slowly changing dimension](https://en.wikipedia.org/wiki/Slowly_changing_dimension).

There are ways to make this easier down the road. For example, tools like DBT let you define queries that get the relevant data for the current day (rather than having to worry about time), and then make the SCD by running merges for every day across time.

For now, a nice option for getting the data in might be joining it directly into the fact table. This hopefully should work pretty well for the RT urls, since the metrics that need it should just need it from fact_daily_feeds?!

**Review by machow — APPROVED** [review]
Thanks for being so patient on this! (I sanity checked the SQL by running the original and new code, and double checking that they returned the same number of rows)

**Pull request merged**
