### PR TITLE
docs(developers): overview of data services architecture

### PR DESCRIPTION
**Pull request by lauriemerrell**
# Overall Description

Migrating the Google Drawing about the data services architecture to Mermaid / Markdown to integrate it into the docs.

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [x] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). Also mention any issues that are partially addressed or are related.

## Docs changes checklist

- [x] Include this section whenever any change in the `docs` folder occurs, otherwise please omit this section.
- [x] **If you haven't already, review the [Contribute to the Docs](https://docs.calitp.org/data-infra/contribute/overview.html) section of the data services documentation for best practices, common formatting, and more**
- [ ] Make sure the preview website was able to be generated
- [ ] Fill out the following section describing what docs were added/updated

This PR updates the `architecture/architecture_overview` in order to integrate our existing architecture diagram into the docs. It also updates the TOC to get the page into navigation.

### CODE REVIEW

**Comment by lauriemerrell** [comment]
It looks like to support this in our Sphinx docs we would need an additional package. See: https://github.com/mgaitan/sphinxcontrib-mermaid. 

Three options here:
1. Install that package and host this in the docs
2. Just host the diagram in GitHub (since their Markdown supports Mermaid) and link to it in the docs (for example, create `ARCHITECTURE.md` in the root of the repo) 
3. Host the diagram in GitHub but print out a static image (ex. PNG) to put in the docs (similar to what E has already done for example for the Airtable ERD diagrams)

**Review by atvaccaro — APPROVED** [review]
do you mind adding a link from the README to the file in github

**Comment by lauriemerrell** [comment]
> do you mind adding a link from the README to the file in github

Will do once we confirm where it is landing -- whether or not we will be adding Mermaid support for Sphinx or just adding this somewhere else

**Comment by lauriemerrell** [comment]
@charlie-costanzo -- wondering if you know how to install that package. From their documentation it seems like we would need to [install](https://github.com/mgaitan/sphinxcontrib-mermaid#installation) and then [configure](https://github.com/mgaitan/sphinxcontrib-mermaid#markdown-support) it, and I'm not sure where exactly that would happen 😅

**Comment by lauriemerrell** [comment]
I think I messed up the git branching / rebasing, going to just re-do in a new PR 😅

**Pull request closed without merging**
