### PR TITLE
Create validation_code_metrics

### PR DESCRIPTION
**Pull request by machow**
Addresses https://github.com/cal-itp/notebooks/issues/20

See https://metabase.k8s.calitp.jarv.us/dashboard/2

### CODE REVIEW

**Comment by hunterowens** [comment]
oh this is super cool 

one additional item - can we add which agency is loosing or gain validation errors? maybe line chart of agency errors?

**Comment by machow** [comment]
I've started a simple metabase question aimed at plotting agencies with changes to number of errors, but it's still pretty rough!

https://metabase.k8s.calitp.jarv.us/question/10/notebook

**Comment by hunterowens** [comment]
to nuance this, rather than doing `sum(errors)`, we would should do `count(distinct(error) GROUP BY feed/agency` so that, for each error / agency combo, we get a count of 1, no matter how many times that error / agency combo occurs since each row in data w/ an error currently equals 1 error, which means that for agencies w/ 100,000 of stop time, 100,000 possible errors.

**Comment by machow** [comment]
(copied from slack)

@Nkdiaz here's a screencast showing how run SQL code in this PR, and make it into a BigQuery table (to test before merging into the pipeline).

(I pushed the small fix to table names mentioned in the screencast.)

Do you mind creating the table views.validation_code_metrics with your SQL, and then updating the metabase dashboard? Once that's done, let me know and we can merge into pipeline!

https://www.loom.com/share/2864d451ede84490865895144b8cd69d

**Comment by Nkdiaz** [comment]
@machow Table views.validation_code_metrics has been created in BitQuery, and metabase dashboard updated with agenc y widget. Available to merge into pipeline

**Comment by machow** [comment]
LGTM! I took out a date range I put in for testing, and will merge now..!

**Pull request merged**
