### PR TITLE
Retrieve agency secrets from repository secret

### LINKED ISSUE #247: fix running generate_provider_list on dev
Currently, we...

* fill in API keys in airflow/data/agencies.yml
* upload the filled file to a gcs airflow bucket, as data/agencies.yml
* upload the original unfilled file as data/agencies_raw.yml

However, as a relic from when we didn't have to fill in agencies.yml,  the dev airflow looks for agencies.yml and agencies_raw.yml on the local disk (which is volume mounted). This means that you have to manually copy these files into airflow/data in the local repo.

We should either...

* add instructions for running this task (e.g. run something in `/script` etc...), OR
* modify the task so that it just downloads from the prod bucket (e.g. with an option to use the current local behavior)

### LINKED ISSUE #622: Security vulnerability: some API keys for downloading GTFS files could be accessed without authentication/authorization
**Describe the bug**

A link to a google sheet that lists some "secret" API keys for downloading GTFS files is exposed in plain text in code.

**To Reproduce**

See discussion on slack due to sensitive nature of this issue.

**Expected behavior**

Environment variables should be used to fill out the keys instead of a publicly-available google sheet.

**Additional context**

The API keys should probably be rotated.

### PR DESCRIPTION
**Pull request by evansiroky**
Following-up on the conversation in https://github.com/cal-itp/data-infra/pull/539#discussion_r741987162, I have moved the discussion about using repository secrets to obtain API keys.

Fixes #247
Fixes #622

### CODE REVIEW

**Comment by hunterowens** [comment]
Sorry for being late to this conversation, anyways, here's my 2 :dollar:: 

Thankfully, these are read only credentials (ie, only allow us to read the API) so the risk of exposure is fairly low. Moving to github secrets for now SGTM, as long as @evansiroky is good plugging / managing the process to update change etc. 

coming down the pipe as we add more realtime feeds is many more API keys to manage. Unfortunately for each swiftly client we will need our own key. 

longer term, I suspect we will want some sort of management process (airtable? etc) to track these, but I'm fine w/ moving to GH secrets to keep the 3 keys we have more secure right now, since I suspect the number of API keys we need to mange will grow. But we can research etc.

**Comment by machow** [comment]
Makes sense to me, if @evansiroky is up for owning the keys / key entering process. I think the main challenge with this setup, is that he will need to store the keys somewhere else, or pull the API keys from the injected agencies.yml when it needs to be updated.

We have a jarvus bitwarden account we can store them in, and there are useful options like bitcrypt (cc @themightychris ) if we want to commit them to the repo. If non-technical users will be handling the api keys, then a sheet or airtable is likely a bit more their speed.

**Comment by themightychris** [comment]
GitHub secrets seems like the best place for now. Humans can't easily pull secrets back out of GitHub Secrets, so we like to have secrets backed up in Jarvus' BitWarden/VaultWarden server as well. We have a CalITP team set up already that everyone should have access to. If anyone interested doesn't have an account yet, please DM me on Slack and we'll get you access.

On a related note, for anything that will run under Kubernetes we have [sealed secrets](https://github.com/bitnami-labs/sealed-secrets) implemented on the cluster which allows us to just commit encrypted secret files directly to the public GitHub repository and they get magically decrypted into regular Kubernetes Secret objects after they're pushed to the cluster

**Review by machow — APPROVED** [review]
See my above comments!

**Comment by evansiroky** [comment]
I am fine with maintaining these secrets. I have gone ahead and deleted the public Google Sheet and have stored the data elsewhere (see internal chat), so I am going to merge this now.

**Pull request merged**
