### PR TITLE
Payments Data ELT Docs and Operators 

### PR DESCRIPTION
**Pull request by hunterowens**
This PR starts a docs section for payments data. 

Ref #131

### CODE REVIEW

**Comment by hunterowens** [comment]
@machow would love a review on this-  pretty simple airflow operator to nightly delete and recreate the materialized table for use in metabase et al.

**Comment by machow** [comment]
@hunterowens, do you have the SQL (or actions that were used) to create `cal-itp-data-infra.views.mst_ridership`? We should add everything used to create these tables..!

**TODO**: I've filled out everything for the missing tables below, except for `transaction_data.micropayments`. How is this table defined?

For example, I here's one of the tables listed in bigquery, along with what I think the SQL would be (see [this bigquery doc](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_external_table_statement))...

**Table details**

image


**SQL Code**

```SQL
---
operators: SqlQueryOperator
---

CREATE OR REPLACE EXTERNAL TABLE `transaction_data.device_transactions` OPTIONS (
  format = "csv",
  uris = ["gs://littlepay-data-extract-prod/mst/device-transactions/*.psv"],
  field_delimiter = "|"
)
```

(note that gusty can now use `.sql` files instead of a yaml file w/ sql field)

### Filling in the rest of the tables

AFAIK, here are the rest. I can add to pipeline later today (or tomorrow morning)

**micropayment_device_ids_fare_type**

```SQL
---
operators: SqlToWarehouseOperator
dst_table_name: "transaction_data.micropayment_device_ids_fare_type"
---

SELECT t1.charge_type,
       t1.micropayment_id,
       t1.charge_amount,
       t2.littlepay_transaction_id
FROM `transaction_data.micropayments` as t1
LEFT JOIN `transaction_data.micropayment_device_transactions` as t2 
ON 
t1.micropayment_id = t2.micropayment_id
```

**micropayment_device_transactions**

```SQL
---
operator: operators: SqlQueryOperator
---

CREATE OR REPLACE EXTERNAL TABLE `transaction_data.device_transactions` OPTIONS (
  format = "csv",
  uris = ["gs://littlepay-data-extract-prod/mst/micropayment-device-transactions/*"],
  field_delimiter = "|"
)
```

**Review by machow — CHANGES_REQUESTED** [review]
Left a comment on the PR on how to define each of the parent tables used to create the `mst_ridership_materialized` table.

Do you mind if we make the following changes?

* rename dataset `transaction_data` to `transactions` (or w/e seems like a good description, but w/o the word data).
* rename DAG to `<dataset_name>_loader`
* add a task to create every table involved here (fine if they're all run everyday; I've put most of them in my PR comment)
* rename `update_materialized_table.yml` to be the table name. In this case `mst_ridership`, and switch to be the current code used in the `mst_ridership` view. Will add SQL for this to my PR comment.

(If you want, happy to make the changes and ping you after pushing to this PR)

**Comment by machow** [comment]
rebased against main

**Comment by machow** [comment]
@cvc5185 for views.mst_ridership, add a dependencies field back to payments_loader. See similar transitstacks view

https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/transitstacks.yml#L3-L4

**Comment by machow** [comment]
Alright--from pairing w/ @cvc5185, current plan is...

* I finish up, and open a PR for a pipeline to make full use of the staging project (e.g. no need to write `{{ "dataset.some_table" | table }}` anymore) 
* I rebase this PR against we
* We make sure it runs locally for @cvc5185
* @hunterowens, does the dataset name `payments` work for you? I forgot i had suggested the name `transactions`, but it's quick for us to change!

**Comment by hunterowens** [comment]
payments sounds good to me!

**Comment by machow** [comment]
Note--ran through this with @cvc5185 and set up pre-commit checks. It was working on airflow running in docker. Will have him go over again before we merge.

**Review by machow — APPROVED** [review]
@cvc5185 once we get the files passing pre-commit checks, this LGTM. Can you try checking out this PR and fixing the linter errors?

They're listed in this log: https://github.com/cal-itp/data-infra/pull/184/checks?check_run_id=3109104792

**Pull request merged**
