### PR TITLE
docs: update transit DB ERD

### PR DESCRIPTION
**Pull request by e-lo**
- Rename from "stacks" to reflect broader scope
- Link to updated mermaid ERD diagram

### CODE REVIEW

**Comment by machow** [comment]
@e-lo do thanks--this diagram is incredible! It looks we may be able to split it into two graphs, reflecting two "domains", which may be a bit easier to scan: GTFSAssessment* and maybe GTFSDataset tables, and the others (orgs, services, transit components, datasets, etc..).

It looks like it'd be two graphs, with GTFS Dataset being sort 

* Domain 1: GTFS Assessment - many associations w/in itself, and outward to organization, service (and dataset?)
* Domain 2: Orgs, services, components, datasets - many associations w/in itself

(I suspect that depending on the complexity of the ERD for domain 2, dataset might do well as its own graph)

**Comment by machow** [comment]
Here are my two quick passes at splitting (may have errors, but wanted to get the general feel..!). It seems like orgs, services, and datasets

### Orgs, services, stack components, datasets

image

### Assessments

image

**Comment by e-lo** [comment]
@machow yes!  love this.  There is a small error (introduced by myself) in the second one. Standby and I'll try and address that (and also adding color)

**Comment by e-lo** [comment]
## Data

[](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBTZXJ2aWNlOiBcIm1hbmFnZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgU2VydmljZTogXCJvcGVyYXRlc1wiXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBDb250cmFjdDogXCJvd25zXCJcbiAgICBPcmdhbml6YXRpb24gfW8tLW97IENvbnRyYWN0OiBcImhvbGRzXCJcbiAgICBPcmdhbml6YXRpb24gfW8tLW97IFByb2R1Y3Q6IFwic2VsbHNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwiY29uc3VtZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwicHJvZHVjZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwicHVibGlzaGVzXCJcbiAgICBPcmdhbml6YXRpb24gfXwtLW97IENvdW50aWVzOiBcInJlc3BvbnNpYmxlIGZvciByZWdpb25hbCBwbGFubmluZyBpblwiXG5cbiAgICBTZXJ2aWNlIHx8LS18eyBQbGFjZXM6IFwib3BlcmF0ZXMgaW5cIlxuICAgIFBsYWNlcyB9by0tfHsgQ291bnRpZXM6IFwiYXJlIGNvbnRhaW5lZCBpblwiXG4gICAgQ291bnRpZXMgfW8tLXx7IENhbHRyYW5zRGlzdHJpY3RzOiBcImFyZSBjb250YWluZWQgaW5cIlxuXG4gICAgRmFyZVN5c3RlbSB8fC0tfHsgT3JnYW5pemF0aW9uOiBcImFwcGxpZXMgdG9cIlxuXG4gICAgRnVuZGluZ1Byb2dyYW0gfXwtLXx7IFNlcnZpY2U6IFwiZnVuZHNcIlxuICAgIFJpZGVyUmVxdWlyZW1lbnQgfW8tLW97IFNlcnZpY2U6IFwiYXBwbGllcyB0b1wiXG4gICAgRWxpZ2libGl0eVByb2dyYW0gfW8tLW97IFNlcnZpY2U6IFwibGljZW5zZXMgZWxpZ2liaWxpdHkgZm9yXCJcblxuICAgIFNlcnZpY2UgfW8tLW97IEd0ZnNEYXRhc2V0U2VydmljZUNvbXBvbmVudDogXCJyZWZsZWN0ZWQgYnlcIlxuICAgIFNlcnZpY2UgfW8tLW97IEd0ZnNEYXRhc2V0OiBcInJlZmxlY3RlZCBieVwiXG4gICAgR3Rmc0RhdGFzZXRTZXJ2aWNlQ29tcG9uZW50IH1vLS1veyBHdGZzRGF0YXNldDogXCJhZ2dyZWdhdGVkIHRvXCIiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGFya1wiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)

### Assessments

[](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBTZXJ2aWNlOiBtYW5hZ2VzIFxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IHByb2R1Y2VzXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBHdGZzRGF0YXNldDogcHVibGlzaGVzXG5cbiAgICBHdGZzQXNzZXNzbWVudFByb3ZpZGVyQ2hlY2tEYXRhIH1vLS1vfCBHdGZzQXNzZXNzbWVudENoZWNrczogXCJ1c2VzIGNyaXRlcmlhIGZyb20gYVwiXG4gICAgR3Rmc0Fzc2Vzc21lbnREYXRhc2V0Q2hlY2tEYXRhIH1vLS1vfCBHdGZzQXNzZXNzbWVudENoZWNrczogXCJ1c2VzIGNyaXRlcmlhIGZyb20gYVwiXG4gICAgR3Rmc0Fzc2Vzc21lbnREYXRhc2V0U2VydmljZUNoZWNrRGF0YSB9by0tb3wgR3Rmc0Fzc2Vzc21lbnRDaGVja3M6IFwidXNlcyBjcml0ZXJpYSBmcm9tIGFcIlxuXG4gICAgR3Rmc0Fzc2Vzc21lbnRQcm92aWRlckNoZWNrRGF0YSB9fC0tfHsgT3JnYW5pemF0aW9uOiBcImV2YWx1YXRlcyBhdCBhIHBvaW50IGluIHRpbWVcIlxuICAgIEd0ZnNBc3Nlc3NtZW50RGF0YXNldENoZWNrRGF0YSB9by0tfHsgR3Rmc0RhdGFzZXQ6IGV2YWx1YXRlc1xuICAgIEd0ZnNBc3Nlc3NtZW50RGF0YXNldFNlcnZpY2VDaGVja0RhdGEgfW8tLXx7IEd0ZnNEYXRhc2V0U2VydmljZUNvbXBvbmVudDogZXZhbHVhdGVzXG5cbiAgICBHdGZzQXNzZXNzbWVudFByb3ZpZGVyQ2hlY2tEYXRhIH18LS18eyBHdGZzUHJvdmlkZXJBc3Nlc3NtZW50OiBcImNvbnRhaW5zIGluZm8gZnJvbVwiXG4gICAgR3Rmc0Fzc2Vzc21lbnREYXRhc2V0Q2hlY2tEYXRhIH1vLS18eyBHdGZzUHJvdmlkZXJBc3Nlc3NtZW50OiBcImNvbnRhaW5zIGluZm8gZnJvbVwiXG4gICAgR3Rmc0Fzc2Vzc21lbnREYXRhc2V0U2VydmljZUNoZWNrRGF0YSB9by0tb3sgR3Rmc1Byb3ZpZGVyQXNzZXNzbWVudDogXCJjb250YWlucyBpbmZvIGZyb21cIlxuXG4gICAgR3Rmc0Fzc2Vzc21lbnREYXRhc2V0Q2hlY2tEYXRhIH1vLS18eyBHdGZzRGF0YXNldEFzc2Vzc21lbnQ6IFwiY29udGFpbnMgaW5mbyBmcm9tXCJcbiAgICBHdGZzQXNzZXNzbWVudERhdGFzZXRTZXJ2aWNlQ2hlY2tEYXRhIH1vLS18eyBHdGZzRGF0YXNldEFzc2Vzc21lbnQ6IFwiY29udGFpbnMgaW5mbyBmcm9tXCJcblxuICAgIFNlcnZpY2UgfW8tLW97IEd0ZnNEYXRhc2V0U2VydmljZUNvbXBvbmVudDogXCJyZWZsZWN0ZWQgYnlcIlxuICAgIFNlcnZpY2UgfW8tLW97IEd0ZnNEYXRhc2V0OiBcInJlZmxlY3RlZCBieVwiXG4gICAgR3Rmc0RhdGFzZXRTZXJ2aWNlQ29tcG9uZW50IH1vLS1veyBHdGZzRGF0YXNldDogXCJhZ2dyZWdhdGVkIHRvXCJcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkYXJrXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

### Transit Stacks

[](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBTZXJ2aWNlOiBcIm1hbmFnZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgU2VydmljZTogXCJvcGVyYXRlc1wiXG4gICAgT3JnYW5pemF0aW9uIH1vLS1veyBDb250cmFjdDogXCJvd25zXCJcbiAgICBPcmdhbml6YXRpb24gfW8tLW97IENvbnRyYWN0OiBcImhvbGRzXCJcbiAgICBPcmdhbml6YXRpb24gfW8tLW97IFByb2R1Y3Q6IFwic2VsbHNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwiY29uc3VtZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwicHJvZHVjZXNcIlxuICAgIE9yZ2FuaXphdGlvbiB9by0tb3sgR3Rmc0RhdGFzZXQ6IFwicHVibGlzaGVzXCJcblxuICAgIE9yZ2FuaXphdGlvblN0YWNrQ29tcG9uZW50IH1vLi5veyBPcmdhbml6YXRpb246IFwiYXNzb2NpYXRlc1wiXG4gICAgT3JnYW5pemF0aW9uU3RhY2tDb21wb25lbnQgfW8uLm97IFByb2R1Y3Q6IFwiYXNzb2NpYXRlc1wiXG4gICAgT3JnYW5pemF0aW9uU3RhY2tDb21wb25lbnQgfW8uLm97IENvbXBvbmVudDogXCJhc3NvY2lhdGVzXCJcbiAgICBPcmdhbml6YXRpb25TdGFja0NvbXBvbmVudCB9by4ub3sgQ29udHJhY3Q6IFwiYXNzb2NpYXRlc1wiXG5cbiAgICBPcmdhbml6YXRpb25TdGFja0NvbXBvbmVudFJlbGF0aW9uc2hpcCB9by4ub3sgT3JnYW5pemF0aW9uU3RhY2tDb21wb25lbnQ6IGNvbXBvbmVudEFcbiAgICBPcmdhbml6YXRpb25TdGFja0NvbXBvbmVudFJlbGF0aW9uc2hpcCB9by4ub3sgT3JnYW5pemF0aW9uU3RhY2tDb21wb25lbnQ6IGNvbXBvbmVudEIiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGFya1wiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)

**Review by machow — APPROVED** [review]
This looks great--thanks! I'll add to the weekly all-hands docs, in case anyone is curious to see!

**Pull request merged**
