### PR TITLE
Switch all get_fs references to data-infra package

### PR DESCRIPTION
**Pull request by SorenSpicknall**
# Description

Related to [this change in calitp-py](https://github.com/cal-itp/calitp-py/pull/105), this updates all outstanding get_fs function imports and references to use the version sourced from calitp-data (rather than calitp-data-infra), and updates the referenced version number for calitp-data-infra throughout. This should not be merged until the new version of calitp-data-infra has been published on PyPI.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## How has this been tested?
Reference changes tested ad hoc

## Post-merge follow-ups
- [x] No action required
- [ ] Actions required (specified below)

### CODE REVIEW

**Review by atvaccaro — CHANGES_REQUESTED** [review]
Did you manually edit these or update with `poetry add ...`? `poetry add` will also updated the lockfile with the actual versions installed.

Also, you shouldn't need to include `calitp-data` since it's already required by `calitp-data-infra`.

Are you planning to also update and test new versions of the images that are changing?

**Review by atvaccaro — CHANGES_REQUESTED** [review]
Did you manually edit these or update with `poetry add ...`? `poetry add` will also updated the lockfile with the actual versions installed.

Also, you shouldn't need to include `calitp-data` since it's already required by `calitp-data-infra`.

Are you planning to also update and test new versions of the images that are changing?

**Comment by SorenSpicknall** [comment]
> Did you manually edit these or update with `poetry add ...`? `poetry add` will also updated the lockfile with the actual versions installed.
> 
> Also, you shouldn't need to include `calitp-data` since it's already required by `calitp-data-infra`.
> 
> Are you planning to also update and test new versions of the images that are changing?

Now that we've got the new calitp-data-infra package version released, I was able to get all our automated builds updated and passing. Are there any additional steps you'd advise taking before merge?

**Comment by atvaccaro** [comment]
> Now that we've got the new calitp-data-infra package version released, I was able to get all our automated builds updated and passing. Are there any additional steps you'd advise taking before merge?

Ok cool I think that's one step, but can you test the jobs themselves that rely on the imports? Most should have mypy but I'm not sure that everything does.

**Review by atvaccaro — APPROVED** [review]
approved pending test archiver deploy

**Pull request merged**
