### PR TITLE
Offboarding - clean up email references

### LINKED ISSUE #3370: Offboard former Jarvus and Slalom and Caltrans staff
* Follow-up action after creating offboarding template in #3341 

### Google IAM
**Jarvus / Slalom / Contractors**
- [x] James Lott `james.l@jarv.us` - all permissions not used in last 90 days  - remove `Owner`
- [x] Soren Spicknall `soren.s@jarv.us` - remove `Owner`
- [x] Ryon Coleman `ryon@jarv.us` - remove: `Service Usage Consumer, Storage Admin, Storage Object Viewer`
- [x] Kim Engie `kim.engie@slalom.com`
- [x] James Meadow `james.meadow@slalom.com`
- [x] `alex.malana@slalom.com`
- [x] `alexandria.w@slalom.com`
- [ ] `easall@gmail.com` -- downgrade?

**Caltrans**
- [x] Julian Hernandez  `julian@calitp.org`
- [x] Samantha Lewis `samantha@calitp.org`
- [x] Ben Bressette `ben@calitp.org` - remove `Viewer`

### GitHub
**cal-itp organization / `warehouse-users` / `warehouse-contributors`**
- [x] `james-meadow` (Slalom)
- [x] `ryon` (Jarvus)
- [ ] `lottspot` (Jarvus)
- [x] `SorenSpicknall` (Jarvus)
- [x] `SLewis1120` (Caltrans)
- [ ] `julianofhernandez` (Caltrans)

**GitHub code references**
- [x] https://github.com/cal-itp/data-infra/blob/main/ci/pyproject.toml
- [x] https://github.com/cal-itp/data-infra/blob/main/packages/calitp-data-infra/pyproject.toml
- [x] https://github.com/cal-itp/data-infra/blob/main/packages/calitp-data-analysis/pyproject.toml
- [x] https://github.com/cal-itp/data-infra/blob/main/apps/maps/pyproject.toml
- [ ] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/download_gtfs_schedule_v2/email_download_failures.py
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/parse_littlepay/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/sync_littlepay/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/deploy_dbt_docs/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/create_external_tables/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/transform_warehouse_full_refresh/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/publish_open_data/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/parse_and_validate_rt_v2/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/download_gtfs_schedule_v2/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/unzip_and_validate_gtfs_schedule_hourly/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/transform_warehouse/METADATA.yml
- [x] https://github.com/cal-itp/data-infra/blob/main/airflow/dags/scrape_feed_aggregators/METADATA.yml

### PR DESCRIPTION
**Pull request by tiffanychu90**
# Description

_Describe your changes and why you're making them. Please include the context, motivation, and relevant dependencies._

Resolves #3370

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [x] Other - clean up email references for former contractors. No longer need email alerts [ct-bdat-internal Slack thread](https://cal-itp.slack.com/archives/C02MJRY8SBB/p1716487136080069?thread_ts=1716486809.472209&cid=C02MJRY8SBB) 

## Post-merge follow-ups

_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track resolution._

- [x] No action required
- [ ] Actions required (specified below)

### CODE REVIEW

**Comment by tiffanychu90** [comment]
> The following changes will be applied to the production Kubernetes cluster upon merge.
> 
> **BE AWARE** this may not reveal changes that have been manually applied to the cluster getting undone—applying manual changes to the cluster should be avoided.
> 
> No manifest changes found for prod.

@vevetron: Which change did I make to do this? How do I not kill Kubernetes cluster?

**Comment by vevetron** [comment]
> @evansiroky: can I remove [this DAG completely](https://github.com/cal-itp/data-infra/blob/offboarding/airflow/dags/download_gtfs_schedule_v2/email_download_failures.py) because everyone in the email list is getting removed? Instead of an `if/else` to print a log, I can remove the entire DAG. Do I need to update anything else so I don't break Airflow?

I think it might be worth keeping the dag for possible future development.

**Review by vevetron — APPROVED** [review]
LGTM

**Comment by vevetron** [comment]
> > The following changes will be applied to the production Kubernetes cluster upon merge.
> > **BE AWARE** this may not reveal changes that have been manually applied to the cluster getting undone—applying manual changes to the cluster should be avoided.
> > No manifest changes found for prod.
> 
> @vevetron: Which change did I make to do this? How do I not kill Kubernetes cluster?

I'm not sure why this came up, I think everything is fine.

**Pull request merged**
