### PR TITLE
WIP: Daily Blackcat Downloader 

### PR DESCRIPTION
**Pull request by hunterowens**
This is an initial stub of a daily blackcat ETL function that creates a daily backup on GCS. Still a bit unsure on how to make it a task using gusty so that is the todo.

### CODE REVIEW

**Comment by machow** [comment]
In case it's useful, I think the two gusty steps are...

1. update dags.py to include a path to the `blackcat` folder [here](https://github.com/cal-itp/data-infra/blob/blackcat-etl/airflow/dags/dags.py#L21)
2. copy out the yaml header from another task, and set `download_and_save_blackcat` in the python_callable field.

**Comment by hunterowens** [comment]
depends on #43

**Comment by machow** [comment]
@hunterowens what's the priority on this? (Is this a thing that becomes important for payments data?)

**Comment by machow** [comment]
Closing since this is 5 months old. Happy to work on this if it's still relevant (and we lay out in an issue)

**Pull request closed without merging**
