### PR TITLE
WIP (docs): add max_bytes, analytics examples

### PR DESCRIPTION
**Pull request by tiffanychu90**
* max_bytes issue when querying (GH issues: #604, #594)
* add to analytics examples section (GH issues: #725)

### CODE REVIEW

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Can you reproduce this error: https://github.com/cal-itp/data-infra/blob/dfbea43efc4fa146e7e73ea285b4e10fdec0dc6c/docs/analytics_examples/test-query.ipynb

I thought `isin` worked with a string, or has in the past? But not sure it's throwing an AssertionError here

**Comment by charlie-costanzo** [comment]
> I thought `isin` worked with a list, or has in the past? But not sure it's throwing an AssertionError here

Hey @tiffanychu90! yeah I got the same error. I used 'collect()' to turn the table into a DataFrame earlier in the query, before the filtering, and got it to run

```
lossan_county_stops = (tbl.views.transitstacks()
                       >> collect()
                       >> filter(_.county.isin(lossan_counties))
                       >> select(*(info_cols + vehicle_cols))
                      )
```

**Comment by tiffanychu90** [comment]
@charlie-costanzo: This work is ready to be massaged to fit the previous tutorial. I left it as a distinct doc because it's missing Metabase and SQL versions of the example. But, if someone else adds those, I'm sure it can live in the `warehouse_tutorials` instead of by itself. It's erroring because there's not JupyterBook html for this tutorial, but it is in the `_toc.yml`

**Comment by charlie-costanzo** [comment]
@tiffanychu90 heck yeah this looks great! I think I'd like to merge this soon and then work on massaging it into the existing tutorial after, like you mentioned. I'm almost done reformatting that now so it should be pretty easy to incorporate this. 

Quick question - what did you mean by It's erroring because there's not JupyterBook html for this tutorial? Happy to help get it to build and then merge!

**Comment by tiffanychu90** [comment]
@charlie-costanzo 
> Quick question - what did you mean by It's erroring because there's not JupyterBook html for this tutorial? Happy to help get it to build and then merge!

This is the error in the build fail: `WARNING: Execution Failed with traceback saved in /home/runner/work/data-infra/data-infra/docs/_build/html/reports/new_tutorial.log`

**Comment by charlie-costanzo** [comment]
@machow do you know where these logs are stored?

`/home/runner/work/data-infra/data-infra/docs/_build/html/reports/new_tutorial.log`

**Comment by charlie-costanzo** [comment]
hey @tiffanychu90 - so I took a look and I think that this is failing to build because we need to install the requirements for `geopandas` and `shapely` in the jupyterbook. I'm going to do that and try to get this merged today!

**Comment by charlie-costanzo** [comment]
@machow - okay I added the airflow requirements to this PR but the build still broke

**Comment by charlie-costanzo** [comment]
geeze okay I finally got this to build @tiffanychu90 and @machow  - it started as a packages issue and turned into an issue with the build timing-out because the new cell blocks were taking a long time to execute. I fixed it in `docs/_config.yml` with:
```
execute:
  timeout: -1
```
to remove the time cap.

Now it's taking a little longer to build but it's working. We should consider improving the time this takes in the future, but I think we are ready to merge this PR for now @holly-g

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Thanks for getting it to build! Maybe as a quick fix...instead of displaying the table at the end of the query, can you change it to be `lossan_stops.head()` from `lossan_stops` or something? I set the max rows displayed earlier to be 10, but maybe it's just faster to display the head anyway.

**Comment by tiffanychu90** [comment]
@holly-g: I wasn't able to get the build to go any faster...so I think this PR is ready to be merged!

**Review by holly-g — APPROVED** [review]
Thanks, Tiffany -- this looks wonderful!

**Pull request merged**
