### PR TITLE
Docs: added new section for beginner analysts

### PR DESCRIPTION
**Pull request by amandaha8**
# Overall Description
A new section will be added to the Docs, which contains tutorials for analysts who are new to Python. 

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes

## Docs changes checklist

- [X ] **If you haven't already, review the [Contribute to the Docs](https://docs.calitp.org/data-infra/contribute/overview.html) section of the data services documentation for best practices, common formatting, and more**
- [x] Make sure the preview website was able to be generated
- [X] Fill out the following section describing what docs were added/updated

This PR adds a new section called `analytics_new_analysts` in order to go over some of the pandas and geopandas skills analysts can expect to use.

### CODE REVIEW

**Comment by tiffanychu90** [comment]
@amandaha8: Couple notes for docs:
1. Check pages, 2 sets of for "next", "previous" arrows? I saw it on Data Analysis Intro / Intermediate, Data Analysis Intermediate, Spatial Analysis Basics / Intro / Intermediate / Advanced. Jupyterbook may have a way to add those navigation buttons already.
2 Data Analysis Intro
* GCS section: can you add a sentence + link to the page where we talk about credentials for GCS
3. Data Management: 
* Some of the hyperlinks to jump down from the top bullet points don't work. 
* Misspellings: "numerous isses", "topolgical", "forumlas", "ie, Number" to be i.e. Number, "aggegrated queries"
4. Geospatial Analysis: Basics
* Use of `my-geojson.parquet` could be `my-geoparquet.parquet` or `my-parquet.parquet` to be more aligned with how other examples given
* Capitalize `EPSG` for `epsg:WGS84`. Do this for all spatial pages.
* Misspellings: "Califonia"
5. Spatial Analysis Intro
* Outdated syntax for spatial join appears a couple times: `join = gpd.sjoin(locations, gdf, how = 'inner', op = 'intersects')`, See [here](https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin.html)
6. Spatial Analysis Intermediate
* Use `gpd.points_from_xy()` instead of `geopandas`, since prior line is `gpd`. Also, update the syntax to be `gdf.to_crs("EPSG:2965")`

**Comment by amandaha8** [comment]
> @amandaha8: Couple notes for docs:
> 
> 1. Check pages, 2 sets of next / previous arrows. I saw it on Data Analysis Intro / Intermediate, Data Analysis Intermediate, Spatial Analysis Basics / Intro / Intermediate / Advanced. Jupyterbook may have a way to add those navigation buttons already.
>    2 Data Analysis Intro
> 
> * GCS section: can you add a sentence + link to the page where we talk about credentials for GCS
> 
> 3. Data Management:
> 
> * Some of the hyperlinks to jump down from the top bullet points don't work.
> * Misspellings: "numerous isses", "topolgical", "forumlas", "ie, Number" to be i.e. Number, "aggegrated queries"
> 
> 4. Geospatial Analysis: Basics
> 
> * Use of `my-geojson.parquet` could be `my-geoparquet.parquet` or `my-parquet.parquet` to be more aligned with how other examples given
> * Capitalize `EPSG` for `epsg:WGS84`. Do this for all spatial pages.
> * Misspellings: "Califonia"
> 
> 5. Spatial Analysis Intro
> 
> * Outdated syntax for spatial join appears a couple times: `join = gpd.sjoin(locations, gdf, how = 'inner', op = 'intersects')`. See [geopandas docs.](https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin.html)
> 
> 6. Spatial Analysis Intermediate
> 
> * Use `gpd.points_from_xy()` instead of `geopandas`, since prior line is `gpd`. Also, update the syntax to be `gdf.to_crs("EPSG:2965")`

**Comment by amandaha8** [comment]
@tiffanychu90 I made all the changes except the link to GCS in data-management page. For some reason the link doesn't work, so I'll will ask you during our one on one.

**Comment by tiffanychu90** [comment]
> @tiffanychu90 I made all the changes except the link to GCS in data-management page. For some reason the link doesn't work, so I'll will ask you during our one on one.

Took a quick look. You'll notice when you scroll and use the "table of contents" sidebar, the header is tagged with `#gcs`, but in the bullet points, it's `#GCS`. Fixing that should allow it to find the right hyperlink within the page.

**Comment by amandaha8** [comment]
> > @tiffanychu90 I made all the changes except the link to GCS in data-management page. For some reason the link doesn't work, so I'll will ask you during our one on one.
> 
> Took a quick look. You'll notice when you scroll and use the "table of contents" sidebar, the header is tagged with `#gcs`, but in the bullet points, it's `#GCS`. Fixing that should allow it to find the right hyperlink within the page.

My bad. It's fixed now!

**Review by charlie-costanzo — APPROVED** [review]
Thank you so much!!

**Pull request merged**
