### PR TITLE
Create remaining RT external tables (and make a couple other small fixes)

### PR DESCRIPTION
**Pull request by atvaccaro**
Important follow-up to this: migrate existing written data to the new entity paths for validation outcomes.
```gsutil -m mv gs://test-rt-parsed/service_alerts_validation_outcomes gs://test-rt-parsed/service_alerts_validations_outcomes```
The above, but in the prod bucket.

# Description

Now that we have RT data, validations, and job outcome records flowing into GCS, we need external tables to query them.

This PR defines a total of 12 external tables.
* 3 file types (sa, tu, vp)
* 2 job types (parse, validate)
* 2 artifact types (actual, outcomes)

Resolves https://github.com/cal-itp/data-infra/issues/1472

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?
Running locally via Airflow dags test.

## Screenshots (optional)
```
[2022-05-05 16:33:07,315] {dagrun.py:477} INFO - Marking run <DagRun create_external_tables @ 2022-04-01 00:00:00+00:00: backfill__2022-04-01T00:00:00+00:00, externally triggered: False> successful
[2022-05-05 16:33:07,318] {dagrun.py:647} WARNING - Failed to record duration of <DagRun create_external_tables @ 2022-04-01 00:00:00+00:00: backfill__2022-04-01T00:00:00+00:00, externally triggered: False>: start_date is not set.
[2022-05-05 16:33:07,321] {backfill_job.py:388} INFO - [backfill progress] | finished run 1 of 1 | tasks waiting: 0 | succeeded: 12 | running: 0 | failed: 0 | skipped: 0 | deadlocked: 0 | not ready: 0
[2022-05-05 16:33:07,324] {backfill_job.py:831} INFO - Backfill done. Exiting.
```

### CODE REVIEW

**Review by lauriemerrell — COMMENTED** [review]
Mostly looks good just a few small Qs:

* Any chance we *do* want to specify `require_partition_filter = True` in the raw data tables? I know the default is `True` but I feel like those tables specifically are the most important ones to have partitioned queries..... Seems safer to explicitly require rather than relying on default. 
* Did you want to move these into an `external_gtfs_rt` dataset per the conversation in Slack? Or are we back to the idea of `unqualified_domain.external_table_name`?

**Comment by atvaccaro** [comment]
> * Any chance we _do_ want to specify `require_partition_filter = True` in the raw data tables? I know the default is `True` but I feel like those tables specifically are the most important ones to have partitioned queries..... Seems safer to explicitly require rather than relying on default.

Yeah let me flip these around. I don't actually like defaulting to True in retrospect.

> Did you want to move these into an external_gtfs_rt dataset per the conversation in Slack? Or are we back to the idea of unqualified_domain.external_table_name?

Yes thanks, I meant to do that.

**Review by lauriemerrell — APPROVED** [review]
LGTM, do we need a follow up ticket to delete old versions of tables that are rendered obsolete by this? Like the current GTFS RT raw data external tables (once those are backfilled) and the `gtfs_rt.external_*` tables? Between dbt and the testing for this, BQ is getting a bit crowded.

**Comment by atvaccaro** [comment]
> LGTM, do we need a follow up ticket to delete old versions of tables that are rendered obsolete by this? Like the current GTFS RT raw data external tables (once those are backfilled) and the `gtfs_rt.external_*` tables? Between dbt and the testing for this, BQ is getting a bit crowded.

Yep! Created https://github.com/cal-itp/data-infra/issues/1481 and https://github.com/cal-itp/data-infra/issues/1482

**Pull request merged**
