### PR TITLE
PyPI Package Release Steps Edits

### LINKED ISSUE #3219: Add pyproject.toml Files to Valid Precursors of PyPI Package Publication
## User story / feature request

As a contributor to Cal-ITP's published Python packages (`calitp-data-infra` and `calitp-data-analysis`), I would like to release a new version of the package when attribution information changes. Since that attribution information is stored in a `pyproject.toml` file one folder above the package itself, it isn't currently picked up by the GitHub Action that detects package changes.

### Acceptance Criteria

When somebody changes information about package authorship, supported Python versions, etc. in the relevant `pyproject.toml` file, it should be considered a publication-relevant change and cause the associated publication workflow to run in CI for that package.

### Notes

This can be achieved by adding a new filepath filter on the existing publication workflows, looking specifically for changes to `pyproject.toml` for the given package.

### PR DESCRIPTION
**Pull request by SorenSpicknall**
# Description

Adds pyproject.toml edits as a valid precursor to PyPI package releases, and updates associated documentation to mention that requirements list updates should prompt a release.

Resolves #3219

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## How has this been tested?

Workflow tested on simulated repo, and docs changes linted successfully.

## Post-merge follow-ups

- [x] No action required
- [ ] Actions required (specified below)

### CODE REVIEW

**Comment by amandaha8** [comment]
Could you add more context? I'm very new to do this so I don't grasp how does this change the process of updating the calitp-data-analysis package?

**Comment by amandaha8** [comment]
That's really neat. So does this change any steps in the process of updating `calitp-data-analysis` in the `data-infra` repo? If so, which steps are altered? https://docs.calitp.org/data-infra/analytics_tools/python_libraries.html#updating-calitp-data-analysis

**Comment by SorenSpicknall** [comment]
> That's really neat. So does this change any steps in the process of updating `calitp-data-analysis` in the `data-infra` repo? If so, which steps are altered? https://docs.calitp.org/data-infra/analytics_tools/python_libraries.html#updating-calitp-data-analysis

Great flag! It doesn't change any process steps, but I added a little extra text in [1e460d5](https://github.com/cal-itp/data-infra/pull/3248/commits/1e460d57769c7aaac661c2b4f62f4999981e44f0) to point people in the right direction if they're trying to make a metadata-only change to the package.

**Comment by amandaha8** [comment]
Hi @SorenSpicknall you can merge it in! Sorry I missed this last week.

**Pull request merged**
