### PR TITLE
Amplitude to Metabase feature branch

### PR DESCRIPTION
**Pull request by machikoyasuda**
# Overall Description

This PR is where all tickets relating to https://github.com/cal-itp/data-infra/milestone/24 the `Amplitude to Metabase` milestone have been merged into, and will close https://github.com/cal-itp/data-infra/issues/960.

## What this PR includes

The following PRs were reviewed and merged into this PR:

1. https://github.com/cal-itp/data-infra/pull/1062
2. https://github.com/cal-itp/data-infra/pull/1121
3. https://github.com/cal-itp/data-infra/pull/1200
4. https://github.com/cal-itp/data-infra/pull/1209
5. https://github.com/cal-itp/data-infra/pull/1239
6. https://github.com/cal-itp/data-infra/pull/1279
- Update to the docs: https://data-infra-1116--cal-itp-previews.netlify.app/datasets_and_tables/overview.html https://data-infra-1116--cal-itp-previews.netlify.app/datasets_and_tables/amplitude.html

## To Test this PR
- `cd airflow`
- Get Amplitude API key and secret key from Amplitude production and add values to `.env`
- Run `airflow` locally
- Open http://localhost:8080/home
- Enable [amplitude_benefits](http://localhost:8080/tree?dag_id=amplitude_benefits)
- Run DAG
- Check for proper data in GCP and Metabase

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [x] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). Also mention any issues that are partially addressed or are related.

## Airflow DAG changes checklist

- [x] Include this section whenever any change to a DAG in the `airflow/dags` folder occurs, otherwise please omit this section.
- [x] Verify that all affected DAG tasks were able to run in a local environment
- [x] Take a screenshot of the graph view of the affected DAG in the local environment showing that all affected DAG tasks completed successfully
- [x] Add/update documentation in the `docs/airflow` folder as needed
- [x] Fill out the following section describing what DAG tasks were added/updated

This PR updates the `amplitude_benefits` DAG in order to....

Adds the following DAG tasks:
- `api_to_jsonl`: Uses the `AmplitudeToFlattenedJSONOperator` to get data from Amplitude API to dataframe. Requires Amplitude API key and secret key. Saves data into the `ingest_amplitude_raw_dev` or `ingest_amplitude_raw_prod` bucket, in the `/benefits/` folder, with a `JSONL` file named with the start and end timestamps.
- `jsonl_bigquery`: Specifies data schema to ingest into BigQuery, in a table called `amplitude.benefits_events`
- `bigquery_to_views`: Users the `SqlToWarehouseOperator` to move data from BigQuery into a view, `views.amplitude_benefits_events`. Only selects the desired data fields and flattens `event_properties` and `user_properties` structs.

image

image
_Last DAG runs are all green_

Updates the following:

- Add `is_development()` to macros, available to use in operators
- Adds `airflow/.env.sample`
- Adds 2 variables to `airflow/docker-compose.yaml`

### CODE REVIEW

**Comment by thekaveman** [comment]
Hi @holly-g, this is our feature branch PR, please don't close! We'll leave it in Draft as we work on sub-tasks in different PRs that target this feature branch `feat-amplitude-operator`

**Comment by holly-g** [comment]
Hi @thekaveman , yes, so sorry about that! Certainly wasn't intentional; (as you may have seen on #data-infra-notify) this got auto-populated in our `QA/Review` column and I had a big red button moment when I accidentally selected all the issues on that column and set them to the `Closed` pipeline..   

Is it all right that I added the `projects-benefits` label here? My thinking was to filter out that label for our own workspace/workflow purposes.

**Comment by thekaveman** [comment]
@holly-g no worries! And yes perfectly fine to label/organize these things as you see fit and whatever works best for the rest of your planning!

We are also using the `Amplitude to Metabase` milestone for tracking purposes...

**Review by lauriemerrell — APPROVED** [review]
LGTM! Thanks for your patience and flexibility with our changing guidance.

**Review by evansiroky — COMMENTED** [review]
Could some documentation be added to the Airflow section of the docs in `docs/airflow` about this DAG? This comment is non-blocking for now as it may make sense to address after merging in the changes within https://github.com/cal-itp/data-infra/pull/1275.

**Pull request merged**
