### PR TITLE
vscode: recommended extensions for docs

### PR DESCRIPTION
**Pull request by themightychris**
Turn off whitespace differences in preview...I also cleaned up the inconsistent tabs/spaces that letting vscode create and edit files manifested

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]
I'm bummed GitHub still hasn't given me access to Codespaces! But I do enjoy using dev containers locally.

**Comment by themightychris** [comment]
@thekaveman oh I didn't even realize that still wasn't GA yet, so you don't have this option in your UI on this repo
Screen Shot 2021-06-07 at 11 24 20 AM
?

**Comment by thekaveman** [comment]
@themightychris that is correct, I do not have that option: 

image


I submitted a request for early access here: https://github.com/features/codespaces

**Comment by themightychris** [comment]
@thekaveman dang I was hoping that once I got it I could "bless"  it in for orgs I worked in like some other GitHub betas--it's not super useful if the team can't use it :-(

**Comment by thekaveman** [comment]
@themightychris I do think the `.devcontainer` setup is useful regardless! I haven't had a chance to try this one locally yet, but over in [cal-itp/benefits](/cal-itp/benefits) I've been using one for local dev since early on and it has been great.

**Pull request merged**
