### PR TITLE
added missing 511 Bay Area real time feeds

### PR DESCRIPTION
**Pull request by mcplanner**
Added regional 511 realtime feeds for Tideline
Added GMV realtime feeds for Emery-go-Round, MVgo

### CODE REVIEW

**Comment by machow** [comment]
@mcplanner does this trillium feed need to be removed? 

https://github.com/cal-itp/data-infra/pull/97/files#diff-504fdf3d4b2c7b3ed2d908d6440733807cf977552333d6140bae36cf5488924eR305

What about here, where the static feed is trillium, but the corresponding RT feed is by 511.org?

https://github.com/cal-itp/data-infra/pull/97/files#diff-504fdf3d4b2c7b3ed2d908d6440733807cf977552333d6140bae36cf5488924eR944

**Comment by hunterowens** [comment]
on hold until we fix #123

**Comment by hunterowens** [comment]
@hunterowens to rebase

**Comment by mcplanner** [comment]
Until 511 indicates otherwise, we should include both Trillium and 511
feeds.

**Comment by mcplanner** [comment]
Is it our policy to review everything we can get our hands on (regional MTC feed, MTC feeds for specific agencies, and feeds agencies publish directly)?

**Comment by machow** [comment]
@mcplanner @hunterowens This is using the old format, and likely will be very challenging to bring up to date. Can we close this PR, and if needed open a new one with all changes needed for agencies.yml?

**Pull request closed without merging**
