### PR TITLE
Improvements to dbt artifacts and publish workflow

### PR DESCRIPTION
**Pull request by atvaccaro**
# Description

Saves dbt artifacts in timestamped partitions in addition to `latest/`.

Improves `publish.py` in a variety of ways: simplifies the logging and configuration; uses env vars for configuration; allows reading manifest from GCS. Also changes documentation to reflect these changes.

Resolves https://github.com/cal-itp/data-infra/issues/1679

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation
- [ ] agencies.yml

## How has this been tested?
Locally, will test in local Airflow before merging.

## Screenshots (optional)
```
[2022-08-30 21:47:15,349] {pod_launcher.py:198} INFO - Event: publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 had an event of type Running
[2022-08-30 21:47:15,514] {pod_launcher.py:149} INFO - reading manifest from gs://test-calitp-dbt-artifacts/latest/manifest.json
[2022-08-30 21:47:15,738] {pod_launcher.py:149} INFO - writing 17 rows to gs://test-calitp-publish/california_open_data__metadata/dt=2022-08-30/ts=2022-08-30T21:47:15.690765Z/metadata.csv
[2022-08-30 21:47:15,918] {pod_launcher.py:149} INFO - writing 172 rows to gs://test-calitp-publish/california_open_data__dictionary/dt=2022-08-30/ts=2022-08-30T21:47:15.690765Z/dictionary.csv
[2022-08-30 21:47:16,066] {pod_launcher.py:149} INFO - handling agency e8f9d49e-2bb6-400b-b01f-28bc2e0e7df2
Downloading: 100%|██████████| 346/346 [00:00<00:00, 2910.73rows/s]
[2022-08-30 21:47:17,526] {pod_launcher.py:149} INFO - writing 346 rows (42.9 kB) from staging_gtfs_schedule.agency to gs://test-calitp-publish/california_open_data__agency/dt=2022-08-30/ts=2022-08-30T21:47:15.690765Z/agency.csv
[2022-08-30 21:47:17,715] {pod_launcher.py:149} INFO - would be uploading to https://data.ca.gov e8f9d49e-2bb6-400b-b01f-28bc2e0e7df2 if --publish
...
[2022-08-30 22:25:03,793] {pod_launcher.py:149} INFO - would be uploading to https://data.ca.gov 0e4da89e-9330-43f8-8de9-305cb7d4918f if --publish
[2022-08-30 22:25:05,954] {pod_launcher.py:198} INFO - Event: publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 had an event of type Succeeded
[2022-08-30 22:25:05,954] {pod_launcher.py:311} INFO - Event with job id publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 Succeeded
[2022-08-30 22:25:06,070] {pod_launcher.py:198} INFO - Event: publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 had an event of type Succeeded
[2022-08-30 22:25:06,070] {pod_launcher.py:311} INFO - Event with job id publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 Succeeded
[2022-08-30 22:25:06,290] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=publish_open_data, task_id=publish_california_open_data, execution_date=20220822T000000, start_date=20220826T173842, end_date=20220830T222506
```

### CODE REVIEW

**Review by lauriemerrell — CHANGES_REQUESTED** [review]
Basically all just typo/clarity things, but one inline is a legit typo.

1. There's a section higher up on the publishing docs page that says:

   > Generally, we recommend executing the dbt models locally and using your local
artifacts to produce the data to be generated; this ensures the data is
up-to-date and fits nicely into a tool-enabled manual workflow.

   Is this still true after this PR?

2. In your example output it says:

   > `poetry run python scripts/publish.py publish-exposure california_open_data --manifest ./target/manifest.json
reading manifest from ./target/manifest.json
would be writing to gs://test-calitp-publish/california_open_data__metadata/dt=2022-08-30/ts=2022-08-30T20:50:52.193951Z/metadata.csv
would be writing to gs://test-calitp-publish/california_open_data__dictionary/dt=2022-08-30/ts=2022-08-30T20:50:52.193951Z/dictionary.csv`

    Why does it say the `would be writing to` for the dictionary & metadata? Wondering if the publish message needs a slight refactor here. I thought those are only generated if you use the `generate documentation` subcommand. 

3. If we refactor in #1725, do we even actually need the `latest` dbt folder? We could just use `get_latest`, right? I guess `latest` is nice for convenience, but just wanted to ask.

**Comment by lauriemerrell** [comment]
> we would want timestamped dictionary/metadata files with the same time as any uploaded data. Is it reasonable to just always save those? document-exposure still exists for iterations on just the docs.

Hmm, I am a bit conflicted about this, because we can't automatically push the metadata & data dictionary to actual CKAN, so there may be things in that folder that weren't actually published to CKAN. (Say we update a docstring but don't actually send that to be updated.)

I guess it depends on what we think the purpose of this folder is (is it an archive of things that were actually on CKAN, or is it an archive of things we generated related to CKAN?). I would maybe want to ask @edasmalchi and @tiffanychu90's opinions here.

**Review by lauriemerrell — COMMENTED** [review]
@atvaccaro still one more docs TODO: 

> I will change it to explain the two options.

Re: local manifest or not.

**Comment by tiffanychu90** [comment]
> > we would want timestamped dictionary/metadata files with the same time as any uploaded data. Is it reasonable to just always save those? document-exposure still exists for iterations on just the docs.
> 
> Hmm, I am a bit conflicted about this, because we can't automatically push the metadata & data dictionary to actual CKAN, so there may be things in that folder that weren't actually published to CKAN. (Say we update a docstring but don't actually send that to be updated.)
> 
> I guess it depends on what we think the purpose of this folder is (is it an archive of things that were actually on CKAN, or is it an archive of things we generated related to CKAN?). I would maybe want to ask @edasmalchi and @tiffanychu90's opinions here.

This is a question about the purpose of the metadata/data dictionary folder, whether it contains archived metadata or only those on CKAN, right? I think the check of timestamped metadata / uploaded data might be too rigorous. My guess is that most metadata errors that need to be fixed from here on out won't be as critical, since the most critical pieces of information had to be submitted/approved. If the changes are these less critical, but still important changes, like having a longer description, updating docstring, etc, it makes sense to push those changes for metadata without triggering an email to Chad. Having that flexibility to make edits to metadata for these non-critical issues to reflect our best working/documenting knowledge is valuable. If we're out of sync with what's on CKAN, it's mostly going to be out of sync for a month at most?

**Comment by tiffanychu90** [comment]
In the case of just updating metadata, would you re-publish all the data so they have the same timestamp then? I do want the metadata to reflect the data at the time of publishing, but also don't want there to be redundant steps in creating the data tables just to fix something in the metadata.

**Comment by atvaccaro** [comment]
> In the case of just updating metadata, would you re-publish all the data so they have the same timestamp then? I do want the metadata to reflect the data at the time of publishing, but also don't want there to be redundant steps in creating the data tables just to fix something in the metadata.

No, there's a separate CLI command to just do metadata. The question here is whether publishing data should also save the metadata/dictionary at time of publish, even if those two files are not live in CKAN.

**Comment by tiffanychu90** [comment]
Ok, then yes, we do want to save that at the time of publishing. Then to Laurie's initial point about archiving or only reflecting what's live in CKAN, I'm leaning towards anything we generate that's CKAN related, even if it's not live.

**Comment by atvaccaro** [comment]
> Ok, with Tiffany's comments, I am comfortable moving forward with this. Sidebar, Lat & Long are different number of places? That seems really weird, but defer to you if that's what you found.

Yes because in California it's all [3 digit negative longitudes](https://www.netstate.com/states/geography/ca_geography.htm) 🤯

**Pull request merged**
