### PR TITLE
Put aggregator checker into airflow

### PR DESCRIPTION
**Pull request by atvaccaro**
closes https://github.com/cal-itp/data-infra/issues/924

Moving code over from https://github.com/cal-itp/gtfs-aggregator-checker, packaging it in an image, and running it via a pod operator. Output is written hive-style to the gtfs data bucket.

I'm not sure I love this image/podoperator pattern for simpler stuff but it's fine and this may grow in complexity over time.

some example ndjson/jsonl output
```
{"url": "https://api.actransit.org/transit/gtfs/download", "url_type": "gtfs_schedule_url", "itp_id": 4, "url_number": 0, "transitfeeds": {"status": "missing"}, "transitland": {"status": "present", "public_web_url": "https://transit.land/feeds/f-9q9-actransit"}}
{"url": "https://api.actransit.org/gtfsrt/vehicles", "url_type": "gtfs_rt_vehicle_positions_url", "itp_id": 4, "url_number": 1, "transitfeeds": {"status": "missing"}, "transitland": {"status": "missing"}}
{"url": "https://api.actransit.org/gtfsrt/alerts", "url_type": "gtfs_rt_service_alerts_url", "itp_id": 4, "url_number": 2, "transitfeeds": {"status": "missing"}, "transitland": {"status": "missing"}}
```

### CODE REVIEW

**Comment by atvaccaro** [comment]
@evansiroky @o-ram how often should this run? Is daily sufficient?

**Comment by evansiroky** [comment]
Daily runs are sufficient

**Review by lauriemerrell — APPROVED** [review]

**Comment by evansiroky** [comment]
oi, just looking at the code of this now. Was there not an easy way to use the `gtfs-aggregator-checker` as a library from pypi? I would really prefer not copy-pasting code from the other repo every time we need to make a change and using the pypi package instead. This way we can also be working towards making sure the `gtfs-aggregator-checker` is easy to use as a package so others in various communities may use it too.

**Comment by atvaccaro** [comment]
I think copy-pasting was a bit lazy in retrospect; I should have brought the git history over as mentioned in another discussion by @themightychris.

I try to strive for repos being aligned around deploy lifecycles rather than trying to draw boundaries around apps/projects. The checker still has its own Docker image which I think is reasonable, since we're heavily using pod operators. Installing it via pypi in the Composer environment adds more complexity to the dependencies and increase the likelihood that we end up with conflicts. A Docker image feels appropriate here as I think the checker is more an "app" than a library or CLI tool; I would expect people to largely use it out-of-the-box and orchestrate it via Airflow or similar, just as we are now.

We can also still deploy to pypi if we want; I just felt that the checker repo was too much overhead when it's likely that code changes will be deployed with infra changes as well. I did flag the old repo as [deprecated](https://github.com/cal-itp/gtfs-aggregator-checker#deprecated-this-project-now-lives-at-httpsgithubcomcal-itpdata-infratreemainjobsgtfs-aggregator-checker).

**Comment by evansiroky** [comment]
This "overhead" is a feature not a bug! The gtfs-aggregator-checker is not intended to be exclusively something used in our data pipeline, but also as a standalone community tool that others in the transit community can use on their own to check for URLs in all of the feed aggregators.

Please remove the deprecated notice from the gtfs-aggregator-checker repo and continue development of checking the aggregators for URLs in the gtfs-aggregator-checker repository. @chriscauley has already published a v1 of gtfs-aggregator-checker to pypi and I want to continue this pattern of releasing to pypi whenever new features are built for gtfs-aggregator-checker. 

As far as the data-infra pipeline goes, I will leave it up to you whether you want to continue using docker or import gtfs-aggregator-checker as a library.

**Pull request merged**
