### PR TITLE
Add service-level check and fct table

### PR DESCRIPTION
**Pull request by owades**
# Description

New check to see whether this guideline is met:
```
100% of trips marked as “Scheduled,” “Canceled,” or “Added” within the Trip Updates feed are represented within the Vehicle Positions feed.
```

I might be able to incorporate the observed_trip data structure proposed [here](https://github.com/cal-itp/data-infra/pull/2205) to reduce the cost of my big join.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?
Not yet

### CODE REVIEW

**Comment by owades** [comment]
@lauriemerrell , could you take a look at this when you are back? I created a new fct table as you suggested, but I'm still using service_key as a unique ID. I think I need some high-level assistance from you - for example, should I be grouping by "provider" rather than "service"? Thank you!

**Comment by lauriemerrell** [comment]
Ok update I missed that @atvaccaro did already make this https://github.com/cal-itp/data-infra/blob/main/warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__services_guideline_index.sql

**Comment by owades** [comment]
Thank you! I think I can get this updated today based on your feedback here.

**Comment by owades** [comment]
@lauriemerrell, this is taking quite a long time to run, I wonder if the join with the BETWEEN statement is slowing stuff down.

**Comment by owades** [comment]
I think I will hold off on this PR until #2205 is done, as it will speed things up dramatically for me.

**Comment by lauriemerrell** [comment]
@owades re:
>  I wonder if the join with the BETWEEN statement is slowing stuff down.

The tables in my sample SQL above are both tiny (~MB), so I don't think that step is the issue -- `fct_vehicle_positions_messages` is a view with no tables in between it and the raw data, so it's going into the filesystem, agree that #2205 will be the big timesaver here.

**Comment by owades** [comment]
starting fresh on new branch

**Pull request closed without merging**
