### PR TITLE
update codeowners per slack discussion

### PR DESCRIPTION
**Pull request by atvaccaro**
see https://jarvus.slack.com/archives/G01R32T28BT/p1674662660541939

* Removing @themightychris per request as well as a couple other outdated owners
* Adding @SorenSpicknall where appropriate
* Combine ownership, trying to keep it relatively high-level and less specific

### CODE REVIEW

**Comment by thekaveman** [comment]
Just randomly coming across this PR, wondering if you can share a little more context for the changes here? Since that Jarvus Slack isn't accessible to most of us in Cal-ITP.

**Comment by atvaccaro** [comment]
> Just randomly coming across this PR, wondering if you can share a little more context for the changes here? Since that Jarvus Slack isn't accessible to most of us in Cal-ITP.

Ah sure, a couple people wanted to stop receiving notifications for certain changes and I just took the opportunity to clean it up in general (we didn't need so much specificity IMO) as well as adding @SorenSpicknall where appropriate!

**Review by lauriemerrell — APPROVED** [review]
Please update the description & just summarize the requested changes, don't think we should have links to the Jarvus Slack (not accessible to all Cal-ITP collaborators), otherwise good to go

**Comment by lauriemerrell** [comment]
Edit: I hadn't even seen @thekaveman's comment when I made mine.... great minds but also I should read PR discussion 😅

**Pull request merged**
