### PR TITLE
ci(docs): add netlify previews

### PR DESCRIPTION
**Pull request by machow**
This PR deploys our doc builds so they can be previewed on netlify. I had to trigger the workflow manually, since it only runs when there are changes to docs, but it appears to have worked! (addresses #623)

* workflow run: https://github.com/cal-itp/data-infra/runs/4270083014?check_suite_focus=true
* preview: https://61982dd5631a9011ef9db73b--cal-itp-previews.netlify.app/intro.html

### TODO:

* @thekaveman , right now it just generates a random string for previews, but I think the `--alias` flag would let us make them more predictable. Is there a convention you want these to follow? :)
* Any sense for how we could add the URL to the PRs (e.g. as info displayed next to the green checkmark / etc..)? cc @themightychris

### CODE REVIEW

**Review by thekaveman — COMMENTED** [review]
The publish looks good!

Do you get any kind of message back with the preview URL? In [this workflow](https://github.com/cal-itp/data-analyses/blob/main/.github/workflows/nbviewer.yml#L24) I used GitHub's API to post a comment back on the PR - could be useful here to post the preview URL so folks know what to look at.

**Comment by machow** [comment]
Yeah--sorry, as I completed a real blockbuster edit I started to worry you had already caught it 😅

**Comment by machow** [comment]
The other day I saw @charlie-costanzo leave a comment on a commit, and then when we opened a PR for it, it somehow turned into a PR comment? Let give it a swing....!

https://docs.github.com/en/rest/guides/working-with-comments#commit-comments

**Comment by thekaveman** [comment]
Yeah check out that link I posted - it used GitHub's Issue Comments API, but apparently that works for PRs too. 

E.g. this page https://docs.github.com/en/rest/reference/pulls says:

> The Pull Request API allows you to list, view, edit, create, and even merge pull requests. Comments on pull requests can be managed via the Issue Comments API.

**Review by thekaveman — APPROVED** [review]
Nice!! 👍

**Comment by thekaveman** [comment]
@angela-tran @machikoyasuda @allejo FYI, deploying a preview to our `cal-itp-previews.netlify.app` site using GH Actions and the `netlify-cli`.

**Comment by machow** [comment]
Thanks for all your help! The snippet for posting was clutch!

**Pull request merged**
